### ISSUE TITLE
Cool nodes. Thank you very much.

### ISSUE THREAD

**Issue by bmf-info** [cubiq/ComfyUI_essentials#2]
Thank you Cubiq for all your nodes, especially Image Enhance Difference.
How about a node for Image Histogram please? Almost all photo editing softwares have that tool to check color, tonal range, and identifies under/overexposed photos, among other things.

Moreover, I can also use the MEAN value with the output image of Image Enhance Difference node to quickly gauge the difference between the original and edited images. The larger the Mean number, the more different they are, while a value of 0 (black output image) means both images are identical.

![2023-11-17 16_49_57-Window](https://github.com/cubiq/ComfyUI_essentials/assets/149558499/10d28110-7356-4236-aa18-5604ada7acb5)

![2023-11-17 17_01_51-Window](https://github.com/cubiq/ComfyUI_essentials/assets/149558499/c438d663-60a6-4a6c-ab51-01ca98ea24a1)

**Comment by cubiq** [comment]
thanks for your message. I often find myself hunting for tiny image differences and a simple mathematical subtraction is not always enough. I noticed that the exponent at .5 is probably too low (ie: the difference is enhanced too much). But setting it to like .7-.9 helps.

Regarding other diagnostic tools. it's certainly possible. The Mean value would be very simple, histograms would be more complicated due to how litegraph wroks (the node library used by comfy). As always the problem is just... time :)

**Comment by bmf-info** [comment]
Thank you I should try .7-.9
I just found your Enhance Difference Node (thank to AI Revolution Discord) and it's pretty cool. Usually I have to place two images side by side and switch back and forth multiple times to compare and find the differences, which takes a lot of time when dealing with many images. This node would simplify my workflow especially for upscaling images I think.
I was actually thinking of suggesting the Mean value first to automatically reject images (that are too different from the original) so the workflow could be sped up even more.
The histogram is just another idea I had, but I'm not familiar with coding so I didn't realize it's more complicated.
