### ISSUE TITLE
mask blur slow and resource intensive

### ISSUE THREAD

**Issue by Botoni** [cubiq/ComfyUI_essentials#20]
mask blur node is slow, it takes several minutes to compute, depending on the blur amount, and while it's at work all cpu 20 threads are at 100% (i7-12700h).

Is that normal? This node is the only that blurs enough to be useful with differential diffusion inpainting.

**Comment by cubiq** [comment]
depends on the image size and the amount of blur, but I have some ideas so speed it up

**Comment by Botoni** [comment]
that would be awesome, your blur node is the best.

**Comment by cubiq** [comment]
now it's much faster, and you can also set the "device" to GPU to make it even faster

**Comment by DmitryKripakov** [comment]
I can confirm that the speed of this node depends on some installed Python dependencies.

In my workflow I just used Mask Blur because it worked very quickly, but yesterday I installed a set of nodes https://github.com/TemryL/ComfyUI-IDM-VTON and https://github.com/AuroBit/ComfyUI- OOTDiffusion and Mask Blur started to work really slowly. It’s 10-15 times slower, and it doesn’t matter what cpu or gpu I use. I have an RTX 4090 and 13900k and I am blurring a short sequence of 512 pixel images.

These nodes required a lot of python packages of certain versions, most likely something broke, but unfortunately I don’t understand what exactly yet, but maybe this will help you understand what could be the reason.
